# ansible/inventory/firewalls.ini

# This is where you define your firewalls.
# After running `terraform apply`, get the public IPs of your
# firewalls from the AWS EC2 console and add them here.

# [group_name]
# hostname_alias   ansible_host=IP_ADDRESS

[firewalls]
fw-az-a   ansible_host=98.84.205.67
fw-az-b   ansible_host=18.214.48.193
