# This is where you define your firewalls.
# After running `terraform apply`, get the public IPs of your
# firewalls from the AWS EC2 console and add them here.

# [group_name]
# hostname_alias   ansible_host=IP_ADDRESS

[firewalls]
fw-az-a   ansible_host=50.16.195.146
fw-az-b   ansible_host=18.205.50.27
