---
- name: Setup APT Caching Proxy on Bastion
  hosts: bastion
  roles:
    - role: apt_cacher

- name: Install Percona Server on all DB hosts via Proxy
  hosts: dbservers
  roles:
    - role: percona

- name: Configure the Primary DB Server
  hosts: vm_private_a1
  become: yes
  vars_files:
    - vars/secrets.yml # Load encrypted variables
  vars:
    # Non-sensitive variables
    replication_user: "repl_user"
    test_db_name: "testdb"
    test_table_name: "widgets"
  tasks:
    - name: Set the root password
      ansible.builtin.command: "mysql -u root -e \"ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';\""
      changed_when: true

    - name: Remove anonymous users
      ansible.builtin.command: "mysql -u root -p'{{ mysql_root_password }}' -e \"DELETE FROM mysql.user WHERE User='';\""
      changed_when: true

    - name: Disallow remote root login
      ansible.builtin.command: "mysql -u root -p'{{ mysql_root_password }}' -e \"DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');\""
      changed_when: true

    - name: Create test database
      community.mysql.mysql_db:
        name: "{{ test_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create test table
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        database: "{{ test_db_name }}"
        query: "CREATE TABLE IF NOT EXISTS {{ test_table_name }} (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"

    - name: Create replication user
      community.mysql.mysql_user:
        name: "{{ replication_user }}"
        host: '%'
        password: "{{ replication_password }}"
        priv: "*.*:REPLICATION SLAVE"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

