---
- name: Update all Debian-based systems
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Only update if cache is older than 1 hour
      tags:
        - update

    - name: Upgrade all installed packages to the latest version
      ansible.builtin.apt:
        upgrade: dist # Use 'dist' to handle kernel upgrades and dependency changes
      tags:
        - upgrade


